name: Android CI

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew --stacktrace
    - name: Test with Gradle
      run: ./gradlew :core:test --stacktrace
    - name: Run Examples
      run: ./gradlew :examples:build --stacktrace
    - name: Build Project
      run: ./gradlew build
